name: colorls
base: core18
version: git
summary: Beautify the terminal's ls command, with color and font-awesome icons
description: |
  Colorizes the ls output with color and icons. Here are the screenshots of
  working example on an iTerm2 terminal (Mac OS), oh-my-zsh with powerlevel9k
  theme and powerline nerd-font + awesome-config font with the Solarized Dark
  color theme.

grade: stable
confinement: classic

parts:
  colorls:
    plugin: dump
    source: .
    override-build: |
      gem build colorls.gemspec
      gem install *.gem -i $SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - libc6-dev
      - make
      - ruby-dev
    stage-packages: [ruby]

apps:
  colorls:
    environment:
      RUBYLIB: $SNAP/usr/lib/ruby/2.5.0:$SNAP/usr/lib/x86_64-linux-gnu/ruby/2.5.0
      GEM_HOME: $SNAP/gems
      GEM_PATH: $SNAP
    command: usr/bin/ruby $SNAP/bin/colorls
